### ISSUE TITLE
Is the pig supposed to move?

### ISSUE THREAD

**Issue by rhaps0dy** [Microsoft/malmo-challenge#33]
From playing the game, I see that the pig moves as pigs move in Minecraft, independent of what actions the agents take, or not take. In some cases, it may be convenient for both agents to wait, not taking any action, until the pig moves itself into a place that is close and easy to catch. Is this allowed?

**Comment by mfuntowicz** [comment]
Hi @rhaps0dy, 

We're enforcing you to do an action as soon as your turn begins. 
You're allowed to wait for the pig to move, without any problem :)

Hope it helps, feel free to reopen if you have any further question.
Morgan

**Comment by rhaps0dy** [comment]
Thank you for your answer!

But I don't understand. These two sentences you wrote seem contradictory. Do you mean that at the beginning of the turn, the evaluator calls `Agent.act` (thus "forcing" the agent to act), but that then `Agent.act` can take as long as it wants to (thus being allowed to wait for the pig) ?

What will you do if the evaluation of the agent takes "too long", and what would you say is too long?

**Comment by mfuntowicz** [comment]
Oh I'm sorry I miss one word ...  :confused: : 

We're **not** enforcing you to do an action as soon as your turn begins.

You'll need to do an action at some point because there is a time limit per episode on Malmo, but your agent can wait before taking its action, for example waiting for the pig to move.

Again, my apologize for this ...
Morgan
